// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFolder(arg1) {
  return window['go']['app']['App']['DeleteFolder'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['app']['App']['DeleteSession'](arg1);
}

export function Filter(arg1) {
  return window['go']['app']['App']['Filter'](arg1);
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function SaveFolder(arg1) {
  return window['go']['app']['App']['SaveFolder'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['app']['App']['SaveSession'](arg1);
}

export function SessionDetail(arg1) {
  return window['go']['app']['App']['SessionDetail'](arg1);
}

export function Tree() {
  return window['go']['app']['App']['Tree']();
}
