// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveConnections() {
  return window['go']['app']['App']['ActiveConnections']();
}

export function CloseTerminal(arg1) {
  return window['go']['app']['App']['CloseTerminal'](arg1);
}

export function ConnectFolder(arg1) {
  return window['go']['app']['App']['ConnectFolder'](arg1);
}

export function ConnectSessions(arg1) {
  return window['go']['app']['App']['ConnectSessions'](arg1);
}

export function CurrentTheme() {
  return window['go']['app']['App']['CurrentTheme']();
}

export function DeleteFolder(arg1) {
  return window['go']['app']['App']['DeleteFolder'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['app']['App']['DeleteSession'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['app']['App']['Disconnect'](arg1);
}

export function DisconnectAll() {
  return window['go']['app']['App']['DisconnectAll']();
}

export function Filter(arg1) {
  return window['go']['app']['App']['Filter'](arg1);
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function ImportITermTheme() {
  return window['go']['app']['App']['ImportITermTheme']();
}

export function OpenTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['OpenTerminal'](arg1, arg2, arg3, arg4);
}

export function PinSession(arg1) {
  return window['go']['app']['App']['PinSession'](arg1);
}

export function PinnedSessions() {
  return window['go']['app']['App']['PinnedSessions']();
}

export function ResolvePrompt(arg1, arg2) {
  return window['go']['app']['App']['ResolvePrompt'](arg1, arg2);
}

export function SaveFolder(arg1) {
  return window['go']['app']['App']['SaveFolder'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['app']['App']['SaveSession'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SessionDetail(arg1) {
  return window['go']['app']['App']['SessionDetail'](arg1);
}

export function SetTerminalWatch(arg1, arg2) {
  return window['go']['app']['App']['SetTerminalWatch'](arg1, arg2);
}

export function Settings() {
  return window['go']['app']['App']['Settings']();
}

export function TermInput(arg1, arg2) {
  return window['go']['app']['App']['TermInput'](arg1, arg2);
}

export function TermResize(arg1, arg2, arg3) {
  return window['go']['app']['App']['TermResize'](arg1, arg2, arg3);
}

export function Theme(arg1) {
  return window['go']['app']['App']['Theme'](arg1);
}

export function Themes() {
  return window['go']['app']['App']['Themes']();
}

export function Tree() {
  return window['go']['app']['App']['Tree']();
}

export function UnpinSession(arg1) {
  return window['go']['app']['App']['UnpinSession'](arg1);
}
