// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connmgr} from '../models';
import {app} from '../models';
import {theme} from '../models';

export function ActiveConnections():Promise<Array<connmgr.Conn>>;

export function CloseTerminal(arg1:string):Promise<void>;

export function ConnectFolder(arg1:string):Promise<void>;

export function ConnectSessions(arg1:Array<string>):Promise<void>;

export function CurrentTheme():Promise<string>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DisconnectAll():Promise<void>;

export function Filter(arg1:string):Promise<Array<app.FilterHit>>;

export function GetVersion():Promise<string>;

export function OpenTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function PinSession(arg1:string):Promise<void>;

export function PinnedSessions():Promise<Array<app.SessionNode>>;

export function ResolvePrompt(arg1:string,arg2:app.PromptReply):Promise<void>;

export function SaveFolder(arg1:app.FolderInput):Promise<string>;

export function SaveSession(arg1:app.SessionInput):Promise<string>;

export function SessionDetail(arg1:string):Promise<app.SessionDetail>;

export function SetTerminalWatch(arg1:string,arg2:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function TermInput(arg1:string,arg2:string):Promise<void>;

export function TermResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Theme(arg1:string):Promise<theme.Theme>;

export function Themes():Promise<Array<string>>;

export function Tree():Promise<app.FolderNode>;

export function UnpinSession(arg1:string):Promise<void>;
