// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function Tree() {
  return window['go']['app']['App']['Tree']();
}
